config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('website.urls'))
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import ListView, DetailView
from . import views

app_name = 'website'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^music/$', views.Music.as_view(), name="music"),
    url(r'^music/album/(?P<pk>[\w-]+)/$', views.Album.as_view(), name="album"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^contact/submit/$',views.submit, name="submit")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

website/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    name = models.CharField('Name', max_length=140)
    cover_art = models.ImageField(upload_to="album_art")
    release_date = models.DateField()

    def __str__(self):
        return self.name

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete='CASCADE')
    name = models.CharField(max_length=100)
    number = models.PositiveIntegerField()

    def __str__(self):
        return self.name

website/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.mail import send_mail
from . import models

# Create your views here.
def home(request):
    return render(request, 'website/home.html', context=locals())

class Music(ListView):
    model = models.Album
    context_object_name = 'music'
    template_name= 'website/music.html'

class Album(DetailView):
    model = models.Album
    context_object_name = 'album'
    template_name = 'website/album.html'

def contact(request):
    return render(request,'website/contact.html', context=locals())

def submit(request):
    if request.method == "POST":
        email = request.POST['email']
        message = request.POST['message']
        reason = request.POST['reason']
        send_mail(
            'Contact from email',
            reason + "\n" + message,
            'web@hyerion.com',
            ['quin@ikhodi.tech',],
            fail_silently=False
        )

        return render(request, 'website/contact.html', { 'success' : "Awesome, we'll contact you" })
    else:
        return render(request, 'website/contact.html', context=locals())

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nullsleep</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
     {% load static %}
    <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
     {% load static %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}/">
</head>
<body>
    {% include "headers.html" %}
    <div class="container">
        <div class="docs-section">
             {% block content %} {% endblock %}
        </div>
        
    </div>

    
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% load static %}
    <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

templates/headers.html
<div class="navbar-spacer"></div>
<nav class="navbar">
    <div class="container">
        <ul class="navbar-list">
            <li class="navbar-item">
                <a class="navbar-link" href="{% url 'website:home' %}">
                    {% load static %}
                    <img src="{% static 'img/nullsleep.gif' %}" alt="Logo" height="48px">
                </a>
            </li>
            <li class="navbar-item">
                <a class="navbar-link" href="{% url 'website:home' %}">Home</a>
            </li>
            <li class="navbar-item">
                <a class="navbar-link" href="{% url 'website:music' %}">Music</a>
            </li>
            <li class="navbar-item">
                <a class="navbar-link" href="{% url 'website:contact' %}">Contact</a>
            </li>
            <!--<li class="navbar-item">
                <a class="navbar-link" href="#" data-popover="#moreNavPopover">All</a>
                <div id="moreNavPopover" class="popover">
                    <ul class="popover-list">
                        <li class="popover-item">
                            <a class="popover-link" href="https://github.com/dhg/Skeleton">On Github</a>
                        </li>
                        <li class="popover-item">
                            <a class="popover-link" href="https://github.com/dhg/Skeleton#browser-support">Browsers</a>
                        </li>
                        <li class="popover-item">
                            <a class="popover-link" href="https://github.com/dhg/Skeleton#license">License</a>
                        </li>
                        <li class="popover-item">
                            <a class="popover-link" href="https://github.com/dhg/Skeleton#extensions">Extensions</a>
                        </li>
                        <li class="popover-item">
                            <a class="popover-link" href="https://github.com/dhg/Skeleton/releases">Versions</a>
                        </li>
                        <li class="popover-item">
                            <a class="popover-link" href="https://github.com/dhg/Skeleton#colophon">Colophon</a>
                        </li>
                    </ul>
                </div>
            </li>-->
        </ul>
    </div>
</nav>

templates/website/album.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="four columns">
            <img src="{{ album.cover_art.url }}" alt="Album Art" height="300px">
        </div>
        <div class="eight columns">
            <table class="u-full-width">
                <thead>
                    <tr>    
                        <th>Number</th>
                        <th>Song Name</th>
                    </tr>
                </thead>
                <tbody>
                    {% for song in album.song_set.all %}
                    <tr>
                        <td>{{ song.number }}</td>
                        <td>{{ song.name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    

        
{% endblock  %}

templates/website/contact.html
{% extends "base.html" %}

{% block content %}
    <p class="success-bar">{{ success }}</p>
    <form action="{% url 'website:submit' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="six columns">
                <label for="exampleEmailInput">Your email</label>
                <input class="u-full-width" name="email" type="email" placeholder="test@mailbox.com" id="exampleEmailInput">
            </div>
            <div class="six columns">
                <label for="exampleRecipientInput">Reason for contacting</label>
                <select class="u-full-width" name="reason" id="exampleRecipientInput">
                    <option value="Questions">Questions</option>
                    <option value="Admiration">Admiration</option>
                    <option value="Can I get your number?">Can I get your number?</option>
                </select>
            </div>
        </div>
        <label for="exampleMessage">Message</label>
        <textarea name="message" class="u-full-width" placeholder="Say something…" id="exampleMessage"></textarea>
        <!--<label class="example-send-yourself-copy">
            <input type="checkbox">
            <span class="label-body">Send a copy to yourself</span>
        </label>-->
        <input class="button-primary" type="submit" value="Submit">
    </form>
{% endblock  %}

templates/website/home.html
{% extends "base.html" %}

{% block content %}
    <h3>Music Runs through us all</h3>
    {% load static %}
    <img src="{% static 'img/main_pic.jpg' %}" alt="">
    <p>Nullsleep (born Jeremiah Johnson October 7, 1980) is an American electronic musician and computer artist currently residing in New York City.
        
    <br>In 1999 he co-founded the low-bit art collective 8bitpeoples, and has served as its lead director
    since its inception. He is best known for his high-energy Game Boy pop songs.Johnson graduated from the Fu Foundation<br>
    School of Engineering and Applied Science at Columbia University in 2003, where he studied computer science and music. <br>He uses Game Boys and NES consoles to create music.</p>
{% endblock  %}

templates/website/music.html
{% extends "base.html" %}

{% block content %}
    <h4>Albums</h4>
    <div class="row">
         {% for album in music %}
            <div class="four columns">
                {% load static %}
                <a href="{% url 'website:album' album.id %}"><img src="{{ album.cover_art.url }}" alt="{{ album.name }}" height="320px"></a> 
                <p>{{ album.name }} | <i><small>{{ album.release_date }}</small></i></p>
                
                <br>
                <a class="button u-full-width" href="{% url 'website:album' album.id %}">View</a>
            </div>
         {% endfor %}
    </div>
    
{% endblock %}